# Generated by Django 3.2.5 on 2021-07-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gbg_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
