# Generated by Django 3.2.5 on 2021-07-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_game_gbg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbb_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('category', 'category'), ('mechanic', 'mechanic'), ('family', 'family'), ('subdomain', 'subdomain')], max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbb_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='max_play_time',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_play_time',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='pitch',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='cat_games', to='main.Label'),
        ),
        migrations.AddField(
            model_name='game',
            name='families',
            field=models.ManyToManyField(related_name='fam_games', to='main.Label'),
        ),
        migrations.AddField(
            model_name='game',
            name='mechanics',
            field=models.ManyToManyField(related_name='mec_games', to='main.Label'),
        ),
        migrations.AddField(
            model_name='game',
            name='subdomains',
            field=models.ManyToManyField(related_name='dom_games', to='main.Label'),
        ),
    ]
