# Generated by Django 3.2.5 on 2021-07-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210728_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='gbb_id',
            new_name='gbg_id',
        ),
    ]
