# Generated by Django 3.2.5 on 2021-07-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_gbb_id_label_gbg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gbb_id',
        ),
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='gbg_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nick',
            field=models.CharField(default='a', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbg_id', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('reviewed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='main.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.player')),
            ],
            options={
                'unique_together': {('player', 'game')},
            },
        ),
    ]
