# Generated by Django 3.2.5 on 2021-07-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210728_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nick',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='review',
            name='gbg_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
