# Generated by Django 3.2.6 on 2021-08-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210729_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('rank',)},
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewed_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
