# Generated by Django 3.2.6 on 2021-08-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210809_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
