# Generated by Django 3.2.6 on 2021-08-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_game_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='area',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
