# Generated by Django 3.2.6 on 2021-08-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_player_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='scraped_at',
            field=models.DateTimeField(null=True),
        ),
    ]
