# Generated by Django 3.2.6 on 2021-08-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_player_scraped_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-rating', '-reviewed_at')},
        ),
        migrations.AddField(
            model_name='player',
            name='game_recs',
            field=models.ManyToManyField(related_name='player_recs', to='main.Game'),
        ),
        migrations.AddField(
            model_name='player',
            name='rec_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='predicted',
            field=models.FloatField(null=True),
        ),
    ]
