# Generated by Django 3.2.6 on 2021-08-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210819_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='reviews_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
