# Generated by Django 3.2.6 on 2021-08-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_player_reviews_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='reviews_scr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='reviews_cnt',
            field=models.IntegerField(null=True),
        ),
    ]
