# Generated by Django 3.2.6 on 2021-08-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210820_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rec_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
