# Generated by Django 4.2.11 on 2024-10-12 11:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('label', models.CharField(max_length=50)),
                (
                    'year',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-2500),
                            django.core.validators.MaxValueValidator(2025),
                        ]
                    ),
                ),
                ('url', models.CharField(max_length=250)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=250, null=True)),
                ('pitch', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_play_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_play_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rec_min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rec_min_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rec_max_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('best_min_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('best_max_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_avg', models.FloatField(blank=True, null=True)),
                (
                    'weight_tag',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('Very Light', 'Very Light'),
                            ('Light', 'Light'),
                            ('Medium', 'Medium'),
                            ('Heavy', 'Heavy'),
                            ('Very Heavy', 'Very Heavy'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ('shop_in_stock', models.BooleanField(blank=True, null=True)),
                (
                    'shop_price',
                    models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
                ),
                ('shop_mean', models.IntegerField(blank=True, null=True)),
                ('shop_saving', models.FloatField(blank=True, null=True)),
                ('shop_outdated', models.BooleanField(default=True)),
                ('shop_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('category', 'category'),
                            ('mechanic', 'mechanic'),
                            ('family', 'family'),
                            ('subdomain', 'subdomain'),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('url', models.CharField(max_length=250, unique=True)),
                ('img', models.CharField(max_length=250)),
                ('in_stock', models.BooleanField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('priced_at', models.DateField(null=True)),
                ('bgg_id', models.IntegerField(blank=True, null=True)),
                ('bgg_missing', models.BooleanField(default=False)),
                ('bgg_scraped', models.DateTimeField(blank=True, null=True)),
                (
                    'game',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='listings',
                        to='main.game',
                    ),
                ),
                (
                    'shop',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='listings',
                        to='main.shop',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='cat_games', to='main.label'),
        ),
        migrations.AddField(
            model_name='game',
            name='families',
            field=models.ManyToManyField(blank=True, related_name='fam_games', to='main.label'),
        ),
        migrations.AddField(
            model_name='game',
            name='mechanics',
            field=models.ManyToManyField(blank=True, related_name='mec_games', to='main.label'),
        ),
        migrations.AddField(
            model_name='game',
            name='shop_best',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cheapest_games',
                to='main.shop',
            ),
        ),
        migrations.AddField(
            model_name='game',
            name='subdomains',
            field=models.ManyToManyField(blank=True, related_name='dom_games', to='main.label'),
        ),
        migrations.CreateModel(
            name='Scrapelog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(max_length=250)),
                ('scraped_at', models.DateTimeField()),
                ('outcome', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                (
                    'day',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='scrapelogs',
                        to='main.day',
                    ),
                ),
            ],
            options={
                'unique_together': {('day', 'target')},
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                (
                    'day',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='prices',
                        to='main.day',
                    ),
                ),
                (
                    'listing',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='prices',
                        to='main.listing',
                    ),
                ),
            ],
            options={
                'unique_together': {('listing', 'day')},
            },
        ),
    ]
