# Generated by Django 3.2.6 on 2021-08-29 06:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbg_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)])),
                ('url', models.CharField(max_length=250)),
                ('rank', models.PositiveIntegerField()),
                ('scraped_at', models.DateTimeField(null=True)),
                ('img', models.CharField(max_length=250, null=True)),
                ('pitch', models.CharField(max_length=256, null=True)),
                ('description', models.TextField(null=True)),
                ('min_players', models.PositiveSmallIntegerField(null=True)),
                ('max_players', models.PositiveSmallIntegerField(null=True)),
                ('min_play_time', models.PositiveSmallIntegerField(null=True)),
                ('max_play_time', models.PositiveSmallIntegerField(null=True)),
                ('min_age', models.PositiveSmallIntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbg_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('category', 'category'), ('mechanic', 'mechanic'), ('family', 'family'), ('subdomain', 'subdomain')], max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbg_id', models.PositiveIntegerField(null=True)),
                ('nick', models.CharField(db_index=True, max_length=256)),
                ('name', models.CharField(max_length=256, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('area', models.CharField(max_length=150, null=True)),
                ('avatar', models.CharField(max_length=256, null=True)),
                ('scraped_at', models.DateTimeField(db_index=True, null=True)),
                ('reviews_cnt', models.IntegerField(null=True)),
                ('reviews_scr', models.FloatField(null=True)),
                ('rec_at', models.DateTimeField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_recs', models.ManyToManyField(related_name='player_recs', to='main.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='cat_games', to='main.Label'),
        ),
        migrations.AddField(
            model_name='game',
            name='families',
            field=models.ManyToManyField(related_name='fam_games', to='main.Label'),
        ),
        migrations.AddField(
            model_name='game',
            name='mechanics',
            field=models.ManyToManyField(related_name='mec_games', to='main.Label'),
        ),
        migrations.AddField(
            model_name='game',
            name='subdomains',
            field=models.ManyToManyField(related_name='dom_games', to='main.Label'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbg_id', models.PositiveIntegerField(db_index=True)),
                ('rating', models.FloatField()),
                ('reviewed_at', models.DateTimeField(db_index=True)),
                ('predicted', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.player')),
            ],
            options={
                'unique_together': {('player', 'game')},
            },
        ),
    ]
