# Generated by Django 4.2.11 on 2024-10-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_accessory',
            field=models.BooleanField(default=False),
        ),
    ]
