# Generated by Django 3.2.6 on 2021-08-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gbg_id',
            new_name='bgg_id',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='gbg_id',
            new_name='bgg_id',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='gbg_id',
            new_name='bgg_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='gbg_id',
            new_name='bgg_id',
        ),
    ]
