# Generated by Django 4.2.11 on 2024-10-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_listing_is_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_second',
            field=models.BooleanField(default=False),
        ),
    ]
