# Generated by Django 3.2.6 on 2021-09-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_game_review_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='bgg_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
