# Generated by Django 4.2.11 on 2024-10-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_rename_is_second_listing_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
