# Generated by Django 3.2.6 on 2021-09-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210902_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('reviews_cnt', models.IntegerField()),
                ('reviews_avg', models.FloatField()),
                ('last_review_id', models.IntegerField()),
                ('last_review_update', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_cnt', models.IntegerField()),
                ('reviews_avg', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='main.day')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='main.game')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='gameday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='main.gameday'),
        ),
    ]
