# Generated by Django 4.2.11 on 2024-10-15 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_alter_listing_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='scraped_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
