# Generated by Django 4.2.11 on 2024-10-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_listing_scraped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_preorder',
            field=models.BooleanField(default=False),
        ),
    ]
