# Generated by Django 3.2.6 on 2021-09-03 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamedays', to='main.day'),
        ),
        migrations.AlterField(
            model_name='gameday',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamedays', to='main.game'),
        ),
    ]
