# Generated by Django 4.2.11 on 2024-10-25 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_listing_is_preorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bgg_scraped',
            new_name='bgg_scraped_at',
        ),
    ]
