# Generated by Django 3.2.6 on 2021-09-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210903_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='review_cnt',
            field=models.IntegerField(null=True),
        ),
    ]
