# Generated by Django 4.2.11 on 2024-10-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_rename_bgg_scraped_listing_bgg_scraped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bgg_looked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
