# Generated by Django 3.2.6 on 2021-09-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_game_review_cnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='review_cnt',
            new_name='reviews_cnt',
        ),
    ]
