# Generated by Django 4.2.11 on 2024-10-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0009_listing_bgg_looked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
