# Generated by Django 3.2.6 on 2021-09-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_review_cnt_game_reviews_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(db_index=True),
        ),
    ]
