# Generated by Django 3.2.6 on 2021-09-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='recs_cnt',
            field=models.IntegerField(null=True),
        ),
    ]
