# Generated by Django 5.1.4 on 2024-12-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0011_remove_listing_is_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Board Game', 'Board Game'),
                    ('Expansion', 'Expansion'),
                    ('X-Wing', 'X-Wing'),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
