# Generated by Django 3.2.6 on 2021-09-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_game_recs_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hotness',
            field=models.FloatField(null=True),
        ),
    ]
