# Generated by Django 5.1.4 on 2024-12-17 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0013_alter_listing_category_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fix_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pageview',
            name='viewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
