# Generated by Django 3.2.6 on 2021-09-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_game_hotness'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='reviews_adj',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameday',
            name='reviews_adj',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
