# Generated by Django 3.2.6 on 2021-09-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210910_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='best_max_players',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='best_min_players',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rec_max_players',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rec_min_age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rec_min_players',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='weight_avg',
            field=models.FloatField(null=True),
        ),
    ]
