# Generated by Django 3.2.6 on 2021-09-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210911_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='weight_tag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
