# Generated by Django 5.1.4 on 2024-12-20 08:16

from django.db import migrations


def rename_dnd(apps, schema_editor):
    Listing = apps.get_model('main', 'Listing')  # Get the Listing model dynamically
    for listing in Listing.objects.filter(category='Dungeons & Dragons').all():
        listing.category = 'RPG'
        listing.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0015_alter_listing_scraped_at'),
    ]

    operations = [
        migrations.RunPython(rename_dnd),
    ]
