# Generated by Django 3.2.6 on 2021-09-15 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_game_weight_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-2500), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
