# Generated by Django 5.1.4 on 2024-12-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0016_auto_20241220_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_accessory',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Board Game', 'Board Game'),
                    ('Expansion', 'Expansion'),
                    ('Bundle', 'Bundle'),
                    ('RPG', 'RPG'),
                    ('X-Wing', 'X-Wing'),
                    ('Shatterpoint', 'Shatterpoint'),
                    ('Star Wars Legion', 'Star Wars Legion'),
                    ('Arkham Horror', 'Arkham Horror'),
                    ('Game of Thrones', 'Game of Thrones'),
                    ('Lord of the Rings', 'Lord of the Rings'),
                    ('Toys', 'Toys'),
                    ('Accessories', 'Accessories'),
                    ('Marvel Champions', 'Marvel Champions'),
                    ('Marvel Crisis Protocol', 'Marvel Crisis Protocol'),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
