# Generated by Django 3.2.6 on 2021-09-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_game_year'),
    ]

    operations = [
        # migrations.RunSQL("""
        #     UPDATE main_review
        #     SET gameday_id = null
        #     WHERE gameday_id IN (7565, 20621, 31592, 245872, 236168, 12384)
        # """),

        migrations.RunSQL("""
            UPDATE main_review 
            SET gameday_id = null
            WHERE id IN (
                SELECT r.id FROM main_review r
                LEFT OUTER JOIN main_gameday g ON r.gameday_id = g.id
            )
        """),

        migrations.RunSQL("""
            DELETE FROM main_gameday WHERE EXISTS (
                SELECT *, count(id) AS cnt
                FROM main_gameday
                GROUP BY day_id, game_id
                HAVING cnt > 1
            )
        """),

        migrations.AlterUniqueTogether(
            name='gameday',
            unique_together={('game', 'day')},
        ),

    ]
