# Generated by Django 5.1.4 on 2025-01-16 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0017_remove_listing_is_accessory_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saffa',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('link', models.URLField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(-2500),
                    django.core.validators.MaxValueValidator(2026),
                ]
            ),
        ),
    ]
