# Generated by Django 3.2.6 on 2021-09-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_gameday_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='reviews_adj',
        ),
        migrations.RemoveField(
            model_name='gameday',
            name='reviews_adj',
        ),
    ]
