# Generated by Django 5.1.4 on 2025-01-23 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0018_saffa_alter_game_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saffa',
        ),
    ]
