# Generated by Django 3.2.6 on 2021-09-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210918_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nick',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
