# Generated by Django 5.1.4 on 2025-05-02 09:13

from django.db import migrations


def rename_toys(apps, schema_editor):
    Listing = apps.get_model('main', 'Listing')  # Get the Listing model dynamically
    for listing in Listing.objects.filter(category='Toys').all():
        listing.category = 'Other'
        listing.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0020_game_is_expansion_alter_listing_category'),
    ]

    operations = [
        migrations.RunPython(rename_toys),
    ]
