# Generated by Django 3.2.6 on 2021-09-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_player_nick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Game of the month', 'Game of the month')], max_length=256)),
                ('description', models.CharField(max_length=256, null=True)),
                ('badge', models.CharField(max_length=256, null=True)),
                ('awarded_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='main.game')),
            ],
        ),
    ]
