# Generated by Django 3.2.6 on 2021-09-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='type',
            field=models.CharField(choices=[('Game of the month', 'Game of the month'), ('Game of the year', 'Game of the year')], max_length=256),
        ),
    ]
