# Generated by Django 3.2.6 on 2021-09-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210921_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_recs',
        ),
        migrations.AlterField(
            model_name='game',
            name='weight_tag',
            field=models.CharField(choices=[('Heavy', 'Heavy'), ('Medium', 'Medium'), ('Light', 'Light')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_at', models.DateTimeField()),
                ('is_primary', models.BooleanField(default=False)),
                ('weight_tag', models.CharField(choices=[('Heavy', 'Heavy'), ('Medium', 'Medium'), ('Light', 'Light')], max_length=20)),
                ('best_players', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recs', to='main.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recs', to='main.player')),
            ],
            options={
                'unique_together': {('game', 'player')},
            },
        ),
    ]
