# Generated by Django 5.1.4 on 2025-06-18 07:56

from django.db import migrations, models


def rename_card(apps, schema_editor):
    Listing = apps.get_model('main', 'Listing')
    for listing in Listing.objects.filter(
        category__in=['Arkham Horror', 'Game of Thrones', 'Lord of the Rings']
    ).all():
        listing.category = 'Card Game'
        listing.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0022_remove_game_fix_me_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Board Game', 'Board Game'),
                    ('Card Game', 'Card Game'),
                    ('Bundle', 'Bundle'),
                    ('RPG', 'RPG'),
                    ('X-Wing', 'X-Wing'),
                    ('Shatterpoint', 'Shatterpoint'),
                    ('Star Wars Legion', 'Star Wars Legion'),
                    ('Accessories', 'Accessories'),
                    ('Marvel Champions', 'Marvel Champions'),
                    ('Marvel Crisis Protocol', 'Marvel Crisis Protocol'),
                    ('Other', 'Other'),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(rename_card),
    ]
