# Generated by Django 3.2.6 on 2021-09-30 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210930_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recs', to='main.game'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='rec_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rec',
            unique_together={('player', 'weight_tag', 'best_players')},
        ),
    ]
