# Generated by Django 5.1.4 on 2025-06-18 08:39

from django.db import migrations, models


def rename_tabletop(apps, schema_editor):
    Listing = apps.get_model('main', 'Listing')
    for listing in Listing.objects.filter(
        category__in=['X-Wing', 'Shatterpoint', 'Star Wars Legion', 'Marvel Crisis Protocol']
    ).all():
        listing.category = 'Tabletop'
        listing.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0024_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Board Game', 'Board Game'),
                    ('Tabletop', 'Tabletop'),
                    ('Card Game', 'Card Game'),
                    ('Bundle', 'Bundle'),
                    ('RPG', 'RPG'),
                    ('Accessories', 'Accessories'),
                    ('Other', 'Other'),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(rename_tabletop),
    ]
