# Generated by Django 3.2.6 on 2021-09-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210930_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='rec',
            name='predicted',
            field=models.FloatField(null=True),
        ),
    ]
