# Generated by Django 5.1.4 on 2025-07-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0025_alter_listing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True, null=True)),
                ('path', models.CharField(max_length=2048)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
