# Generated by Django 3.2.6 on 2021-10-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rec_predicted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameday',
            name='reviews_avg',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='gameday',
            name='reviews_cnt',
            field=models.IntegerField(db_index=True),
        ),
    ]
