# Generated by Django 3.2.6 on 2021-10-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20211001_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mechanic_cluster',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='rec_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='scraped_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
