# Generated by Django 3.2.6 on 2021-11-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20211025_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='redo_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='redo_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='redo_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
