# Generated by Django 5.1.4 on 2026-08-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0028_listing_sleeve_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='restocked_after_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='restocked_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
