# Generated by Django 3.2.6 on 2021-12-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20211130_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.player',),
        ),
    ]
