# Generated by Django 5.1.4 on 2026-09-01 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0029_game_restocked_after_days_game_restocked_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pageview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='day',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='game',
        ),
        migrations.DeleteModel(
            name='VisitorLog',
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
