# Generated by Django 3.2.6 on 2022-01-14 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_playerproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-2500), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
