# Generated by Django 3.2.6 on 2022-06-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0030_alter_game_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ps_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ps_data',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ps_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ps_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ps_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ps_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ps_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
