# Generated by Django 3.2.6 on 2022-06-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20220602_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.RemoveField(
            model_name='game',
            name='ps_mean',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ps_range',
        ),
        migrations.AddField(
            model_name='game',
            name='ps_est_saving',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ps_mean_saving',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ps_min_saving',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='best_max_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='best_min_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='cat_games', to='main.Label'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='families',
            field=models.ManyToManyField(blank=True, related_name='fam_games', to='main.Label'),
        ),
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_play_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='mechanic_cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='mechanics',
            field=models.ManyToManyField(blank=True, related_name='mec_games', to='main.Label'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_play_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='pitch',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='ps_url',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rec_max_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rec_min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rec_min_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='subdomains',
            field=models.ManyToManyField(blank=True, related_name='dom_games', to='main.Label'),
        ),
    ]
