# Generated by Django 3.2.6 on 2022-06-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20220605_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='ps_scraped_at',
            new_name='ps_priced_at',
        ),
    ]
