# Generated by Django 3.2.6 on 2022-06-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_ps_scraped_at_game_ps_priced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ps_url_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
