# Generated by Django 3.2.6 on 2022-06-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_game_ps_url_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'available'), ('out of stock', 'out of stock')], max_length=50)),
                ('price', models.IntegerField()),
                ('priced_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.day')),
            ],
        ),
        migrations.CreateModel(
            name='ShopGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, unique=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('mean_price', models.FloatField(blank=True, null=True)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('mean_saving', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.AlterField(
            model_name='game',
            name='ps_url_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('host', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='shopgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.game'),
        ),
        migrations.AddField(
            model_name='price',
            name='shopgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.shopgame'),
        ),
        migrations.AddField(
            model_name='shopgame',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='shopgame',
            unique_together={('shop', 'game')},
        ),
    ]
