# Generated by Django 3.2.6 on 2022-06-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20220627_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopGameProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Raru price',
                'verbose_name_plural': 'Raru prices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.AddField(
            model_name='shopgame',
            name='mia',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(choices=[('Raru', 'Raru')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shopgame',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
