# Generated by Django 3.2.6 on 2022-06-29 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20220627_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shopgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopgames', to='main.game'),
        ),
        migrations.AlterField(
            model_name='shopgame',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopgames', to='main.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('shopgame', 'day')},
        ),
        migrations.RemoveField(
            model_name='price',
            name='priced_at',
        ),
    ]
