# Generated by Django 3.2.6 on 2022-06-29 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20220629_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopgameproxy',
            options={'verbose_name': 'Shop Raru', 'verbose_name_plural': 'Shop Raru'},
        ),
        migrations.AddField(
            model_name='shopgame',
            name='url_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
