# Generated by Django 3.2.6 on 2022-07-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20220629_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopGameProxy',
        ),
        migrations.CreateModel(
            name='ShopGameRaru',
            fields=[
            ],
            options={
                'verbose_name': 'Shop Raru',
                'verbose_name_plural': 'Shop Raru',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.AddField(
            model_name='game',
            name='shop_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='shop_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='shop_saving',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopgame',
            name='current_available',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
