# Generated by Django 3.2.6 on 2022-07-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20220703_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ps_available',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ps_data',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ps_est_saving',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ps_mean_saving',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ps_min_saving',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ps_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ps_priced_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ps_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ps_url_at',
        ),
    ]
