# Generated by Django 3.2.6 on 2022-08-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20220705_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopGameMav',
            fields=[
            ],
            options={
                'verbose_name': 'Shop Meeps and Veeps',
                'verbose_name_plural': 'Shop Meeps and Veeps',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.CreateModel(
            name='ShopGameTakealot',
            fields=[
            ],
            options={
                'verbose_name': 'Shop Takealot',
                'verbose_name_plural': 'Shop Takealot',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(choices=[('Raru', 'Raru'), ('Takealot', 'Takealot'), ('Meeps and Veeps', 'Meeps and Veeps')], max_length=50, unique=True),
        ),
    ]
