# Generated by Django 3.2.6 on 2022-08-10 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20220802_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopGameTakealot',
        ),
        migrations.CreateModel(
            name='ShopGameTimeless',
            fields=[
            ],
            options={
                'verbose_name': 'Shop Timeless',
                'verbose_name_plural': 'Shop Timeless',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.AddField(
            model_name='award',
            name='num_ratings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='ru_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runnerups', to='main.game'),
        ),
        migrations.AddField(
            model_name='award',
            name='ru_num_ratings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='ru_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(choices=[('Raru', 'Raru'), ('Takealot', 'Takealot'), ('Meeps and Veeps', 'Meeps and Veeps'), ('Timeless', 'Timeless')], max_length=50, unique=True),
        ),
    ]
