# Generated by Django 3.2.6 on 2022-08-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20220810_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
