# Generated by Django 3.2.6 on 2022-08-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_player_last_review_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='mechanic_cluster',
        ),
        migrations.AddField(
            model_name='game',
            name='sim_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='similars',
            field=models.ManyToManyField(to='main.Game'),
        ),
    ]
