# Generated by Django 3.2.6 on 2022-08-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20220815_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopGameGeekhome',
            fields=[
            ],
            options={
                'verbose_name': 'Shop Geekhome',
                'verbose_name_plural': 'Shop Geekhome',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.AlterField(
            model_name='game',
            name='similars',
            field=models.ManyToManyField(related_name='rev_similars', to='main.Game'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(choices=[('Raru', 'Raru'), ('Takealot', 'Takealot'), ('Meeps and Veeps', 'Meeps and Veeps'), ('Timeless', 'Timeless'), ('GeekHome', 'GeekHome')], max_length=50, unique=True),
        ),
    ]
