# Generated by Django 3.2.6 on 2022-08-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20220816_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_review_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
