# Generated by Django 3.2.6 on 2022-09-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_player_last_review_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_outdated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
