# Generated by Django 3.2.6 on 2022-09-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_player_is_outdated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rec',
            unique_together=set(),
        ),
    ]
