# Generated by Django 3.2.6 on 2022-09-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_rec_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='last_review_update',
            new_name='last_review_at',
        ),
        migrations.AddField(
            model_name='day',
            name='is_outdated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='gameday',
            name='is_outdated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
