# Generated by Django 3.2.6 on 2022-10-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20220928_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopGameRenew',
            fields=[
            ],
            options={
                'verbose_name': 'Shop Renew',
                'verbose_name_plural': 'Shop Renews',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.RemoveField(
            model_name='shopgame',
            name='current_available',
        ),
        migrations.RemoveField(
            model_name='shopgame',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='shopgame',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='shopgame',
            name='mean_price',
        ),
        migrations.RemoveField(
            model_name='shopgame',
            name='mean_saving',
        ),
        migrations.RemoveField(
            model_name='shopgame',
            name='min_price',
        ),
        migrations.AddField(
            model_name='game',
            name='shop_outdated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameday',
            name='max_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameday',
            name='mean_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameday',
            name='mean_saving',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameday',
            name='min_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
