# Generated by Django 3.2.6 on 2022-10-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20221019_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='shop_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
