# Generated by Django 3.2.6 on 2022-10-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_game_shop_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameday',
            old_name='mean_price',
            new_name='shop_mean',
        ),
        migrations.RenameField(
            model_name='gameday',
            old_name='mean_saving',
            new_name='shop_saving',
        ),
        migrations.RemoveField(
            model_name='gameday',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='gameday',
            name='min_price',
        ),
        migrations.AddField(
            model_name='game',
            name='shop_mean',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameday',
            name='shop_best',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopgame',
            name='current_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopgame',
            name='current_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
