# Generated by Django 3.2.6 on 2022-12-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20221020_0713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopGameRaru',
        ),
        migrations.CreateModel(
            name='ShopGameTabletopGuru',
            fields=[
            ],
            options={
                'verbose_name': 'Shop Tabletop Guru',
                'verbose_name_plural': 'Shop Tabletop Guru',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.CreateModel(
            name='ShopGameTakealot',
            fields=[
            ],
            options={
                'verbose_name': 'Shop Takealot',
                'verbose_name_plural': 'Shop Takealot',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.CreateModel(
            name='ShopGameTheHiddenDen',
            fields=[
            ],
            options={
                'verbose_name': 'Shop The Hidden Den',
                'verbose_name_plural': 'Shop The Hidden Den',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(choices=[('Raru', 'Raru'), ('Takealot', 'Takealot'), ('Meeps and Veeps', 'Meeps and Veeps'), ('Timeless', 'Timeless'), ('GeekHome', 'GeekHome'), ('The Hidden Den', 'The Hidden Den'), ('Tabletop Guru', 'Tabletop Guru')], max_length=50, unique=True),
        ),
    ]
