# Generated by Django 3.2.6 on 2023-02-06 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20221201_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-2500), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
