# Generated by Django 3.2.6 on 2023-02-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_game_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopGameTakealot',
        ),
        migrations.CreateModel(
            name='ShopGameGargoyle',
            fields=[
            ],
            options={
                'verbose_name': 'Shop Grinning Gargoyle',
                'verbose_name_plural': 'Shop Grinning Gargoyle',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(choices=[('Meeps and Veeps', 'Meeps and Veeps'), ('Timeless', 'Timeless'), ('GeekHome', 'GeekHome'), ('The Hidden Den', 'The Hidden Den'), ('Tabletop Guru', 'Tabletop Guru'), ('Grinning Gargoyle', 'Grinning Gargoyle')], max_length=50, unique=True),
        ),
    ]
