# Generated by Django 3.2.6 on 2023-07-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20230222_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[['own', 'own']], default='own', max_length=50),
            preserve_default=False,
        ),
    ]
