# Generated by Django 3.2.6 on 2024-03-23 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0056_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(-2500),
                    django.core.validators.MaxValueValidator(2025),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(
                choices=[
                    ['own', 'own'],
                    ['prevowned', 'prevowned'],
                    ['wishlist', 'wishlist'],
                    ['none', 'none'],
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bgg_id', models.IntegerField()),
                ('duration', models.IntegerField(null=True)),
                ('num_players', models.IntegerField(null=True)),
                (
                    'day',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='plays',
                        to='main.day',
                    ),
                ),
                (
                    'game',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='plays',
                        to='main.game',
                    ),
                ),
                (
                    'player',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='plays',
                        to='main.player',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
