# Generated by Django 3.2.6 on 2024-03-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0057_auto_20240323_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_played_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='num_plays',
            field=models.IntegerField(default=0),
        ),
    ]
