# Generated by Django 5.0.4 on 2024-04-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0058_auto_20240325_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopGameLevelUp',
            fields=[],
            options={
                'verbose_name': 'Shop Level Up',
                'verbose_name_plural': 'Shop Level Up',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.CreateModel(
            name='ShopGameSwordAndBoard',
            fields=[],
            options={
                'verbose_name': 'Shop Sword and Board',
                'verbose_name_plural': 'Shop Sword and Board',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(
                choices=[
                    ('Meeps and Veeps', 'Meeps and Veeps'),
                    ('Timeless', 'Timeless'),
                    ('GeekHome', 'GeekHome'),
                    ('The Hidden Den', 'The Hidden Den'),
                    ('Tabletop Guru', 'Tabletop Guru'),
                    ('Grinning Gargoyle', 'Grinning Gargoyle'),
                    ('Level Up', 'Level Up'),
                    ('Sword and Board', 'Sword and Board'),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
