# Generated by Django 4.2.11 on 2024-07-05 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0059_shopgamelevelup_shopgameswordandboard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopGameAmazon',
            fields=[],
            options={
                'verbose_name': 'Shop Amazon',
                'verbose_name_plural': 'Shop Amazon',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.game',),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(
                choices=[
                    ('Meeps and Veeps', 'Meeps and Veeps'),
                    ('Timeless', 'Timeless'),
                    ('GeekHome', 'GeekHome'),
                    ('The Hidden Den', 'The Hidden Den'),
                    ('Tabletop Guru', 'Tabletop Guru'),
                    ('Grinning Gargoyle', 'Grinning Gargoyle'),
                    ('Level Up', 'Level Up'),
                    ('Sword and Board', 'Sword and Board'),
                    ('Amazon', 'Amazon'),
                    ('BGBSA', 'BGBSA'),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name='CronSchedule',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotness', models.TextField(null=True)),
                ('hotness_dur', models.FloatField(null=True)),
                ('scrape_games', models.TextField(null=True)),
                ('scrape_games_dur', models.FloatField(null=True)),
                ('update_game_stats', models.TextField(null=True)),
                ('update_game_stats_dur', models.FloatField(null=True)),
                ('train_models_sim', models.TextField(null=True)),
                ('train_models_sim_dur', models.FloatField(null=True)),
                ('scrape_players', models.TextField(null=True)),
                ('scrape_players_dur', models.FloatField(null=True)),
                ('scrape_shop_bgbsa', models.TextField(null=True)),
                ('scrape_shop_bgbsa_dur', models.FloatField(null=True)),
                ('scrape_shop_thd', models.TextField(null=True)),
                ('scrape_shop_thd_dur', models.FloatField(null=True)),
                ('scrape_shop_mav', models.TextField(null=True)),
                ('scrape_shop_mav_dur', models.FloatField(null=True)),
                ('scrape_shop_tl', models.TextField(null=True)),
                ('scrape_shop_tl_dur', models.FloatField(null=True)),
                ('scrape_shop_gh', models.TextField(null=True)),
                ('scrape_shop_gh_dur', models.FloatField(null=True)),
                ('scrape_shop_ttg', models.TextField(null=True)),
                ('scrape_shop_ttg_dur', models.FloatField(null=True)),
                ('scrape_shop_gg', models.TextField(null=True)),
                ('scrape_shop_gg_dur', models.FloatField(null=True)),
                ('scrape_shop_sab', models.TextField(null=True)),
                ('scrape_shop_sab_dur', models.FloatField(null=True)),
                ('scrape_shop_lu', models.TextField(null=True)),
                ('scrape_shop_lu_dur', models.FloatField(null=True)),
                ('scrape_shop_amz', models.TextField(null=True)),
                ('scrape_shop_amz_dur', models.FloatField(null=True)),
                ('scrape_shop_out', models.TextField(null=True)),
                ('scrape_shop_out_dur', models.FloatField(null=True)),
                (
                    'day',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='cron_schedules',
                        to='main.day',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
