name: Deploy Django Application

on:
  push:
    tags:
      - 'v*'  # Trigger deployment when a tag starting with 'v' is pushed (e.g., v1.0, v1.1)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Deploy via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Navigate to your project directory on the server
            cd /home/bgg/bggd

            # Pull the latest changes
            git pull origin main

            # Activate virtual environment
            source /home/bgg/bggd/.venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Apply migrations
            python manage.py migrate --noinput

            # Collect static files
            python manage.py collectstatic --noinput

            # Restart the application (assuming you're using Gunicorn)
#            sudo systemctl restart gunicorn  # Adjust this to your specific WSGI server if different (e.g., uwsgi)
